  - name: Add application User
    ansible.builtin.user:
      name: roboshop

  - name: remove app directory if already present
    ansible.builtin.file:
      path: /app
      state: absent

  - name: setup an app directory
    ansible.builtin.file:
      path: /app
      state: directory

  - name: "Download the {{component}} code"
    ansible.builtin.get_url:
      url: "https://roboshop-builds.s3.amazonaws.com/{{component}}.zip"
      dest: /tmp
      
  - name: unzip application to created app directory
    ansible.builtin.unarchive:
      src: "/tmp/{{component}}.zip"
      dest: /app
      remote_src: yes