  - name: setup the mongodb repo file
    ansible.builtin.copy:
      src: mongo.repo
      dest: /etc/yum.repos.d/mongo.repo

  - name: install mongodb-client
    ansible.builtin.package:
      name: mongodb-org-shell
      state: present 

  - name: "get the catalogue count"
    ansible.builtin.shell: mongo --host mongodb.kiranku.online --quiet --eval 'db = db.getSiblingDB("catalogue"); db.products.count()'
    register: products_count
    when: component == "catalogue"

  - name: "get the user count"
    ansible.builtin.shell: mongo --host mongodb.kiranku.online --quiet --eval 'db = db.getSiblingDB("users"); db.users.count()'
    register: users_count
    when: component == "user"

  # - name: print the count
  #   ansible.builtin.debug:
  #     msg: "product count: {{entries_count}}"

  - name: "load catalogue data"
    ansible.builtin.shell: "mongo --host mongodb.kiranku.online </app/schema/{{component}}.js"
    when: products_count.stdout == "0" and component == "catalogue"
    ignore_errors: true

  - name: "load user data"
    ansible.builtin.shell: "mongo --host mongodb.kiranku.online </app/schema/{{component}}.js"
    when: users_count.stdout == "0" and component == "user"
    ignore_errors: true