  - name: Setup SystemD Catalogue Service
    ansible.builtin.copy:
      src: catalogue.service
      dest: /etc/systemd/system/catalogue.service

  - name: Load the service
    ansible.builtin.systemd_service:
      daemon_reload: true

  - name: Start and enable the service
    ansible.builtin.service:
      name: catalogue
      state: started
      enabled: yes