  - name: "Setup SystemD {{component}} Service"
    ansible.builtin.copy:
      src: catalogue.service
      dest: "/etc/systemd/system/{{component}}.service"

  - name: Load the service
    ansible.builtin.systemd_service:
      daemon_reload: true

  - name: "Start and enable the {{component}} service"
    ansible.builtin.service:
      name: "{{component}}"s
      state: started
      enabled: yes